witseie-elen4010/2022-group-lab-005

- mainRoutes.js
- tests/lobby.test.js
Reviewed my code since the great merge. Fixed a small error. Changed one of  the tests that was failing due to a logic error.
> The great refactor v1 jesse

- src/mainRoutes.js
- src/public/login.js
- src/public/loginAssets.css
- src/services/login_db.js
- src/views/Login.html
Changed login system to use Promises:
* Now the client will wait for the server to reply with its response instead of saying the received data is invalid.
Adapted bootstrap simple form to make a login form:
* If the user inputs invalid characters into the username and/or password field, those fields now have a red boarder around them to indicate that they are invalid.
* This is still similar to the original bootstrap template so we definitely need to adapt it and improve it more to suit our needs. Maybe we can add a boarder around the fields with text in the top left corner describing the input group? Something like this:
Did some refactoring.
What the user sees when they first go to the page
Invalid username (the text above the button is for debug)
Invalid password (the text above the …
> Small changes to login screen UI and backend.

- src/index.js
- src/public/lobby.js
- src/routes/lobbyRoutes.js
- src/services/soc.js
- src/views/lobby.html
The start of the multiplayer communication implementation. Very broken. Do not uncomment or delete!
Related issue: #26
> Multiplayer communication.

- src/public/login.js
- src/services/login_db.js
- src/views/home.html
Cookies added to allow username to be acessed on different web pages. testing code added onto home page
Added functionality to store username inside cookies to be accessed on another page.
> Cookie added

- index.js
- package-lock.json
- package.json
- src/package-lock.json
- src/package.json
- src/routes/lobbyRoutes.js
- src/views/lobby.html
Working on sockets. index.js uses a toggle to enable the code I've added. Setting line 4 to false will run the new code which sets up the sockets.
Related to #23
> Adding support for sockets.

- src/public/guess.css
- src/routes/gameRoutes.js
- src/views/test.html
Change background setup in the /game/guess path
> Change Background Setup

- src/public/game.css
- src/public/game.js
- src/views/game.html
#25 Progress
Added the start of a game board, including css and html files.
> Added basics to begin the game board

- src/public/game.css
- src/public/game.js
#25 update
FEATURES: Backspace working, change of colour blocks, inputting of the text, only letters can be inputted
BUG: Duplicate incorrect position variables not changing colour to yellow.
MISSING: End of game when word is found
> game logic implemented with dummy word variable

- src/public/changeBackground.js
- src/public/fetchBackground.js
- src/public/sendBackgroundToServer.js
- src/public/sendToServer.js
- src/routes/gameRoutes.js
- src/routes/userRoutes.js
- src/services/background_db.js
- src/views/changeBackground.html
Background is logged into database and changed on the game screen
> Background

- src/public/changeBackground.js
- src/public/fetchBackground.js
- src/public/guess.css
- src/views/changeBackground.html
- src/views/game.html
Added stylesheet function to resize images
> Background with Stylesheet

- src/routes/lobbyRoutes.cjs
- src/services/lobby.cjs
- src/views/lobby.html
Adds customisable lobby settings when creating a new game, includes choosing a random word.
#51 
> Lobby creation

- src/services/background_db.cjs
- tests/background.test.js
> Test Improvements

- src/public/game.js
- src/services/socket.cjs
Added support for logging the guesses that are made by a user. The words are saved to the wordLog table in the database.
Fixes #23
> Game communication

- src/public/game.css
- src/public/game.js
- src/services/socket.cjs
- src/views/game.html
Fixed issue with players not being able to connect to the server.
Added a loading icon so that the player knows the server is waiting for the other players to join the session.
Related to #55
> Backend game logic

- src/public/game.css
- src/public/game.js
- src/views/game.html
- changed layouts from tables to divs
- implemented working virtual keyboard
#68
> Starting to finalise layout and fixed virtual keyboard

- package-lock.json
- package.json
- src/public/game.js
- src/public/lobby.js
- src/routes/gameRoutes.cjs
- src/services/socket.cjs
- src/views/lobby.html
Added rudimentary support for players to create and join standard games. There are some small issues that will be addressed in thew next release.
Light refactoring of the socket.cjs file.
To create a game, go to the lobby page, select 'standard', select the number of players (far left is 2 players, far right is 6 players. The slider moves in increments of 1). Click 'create game' and follow the prompts.
Then, open another tab, navigate to the lobby, select the game name from the list and past it into the textbox below. Click join game. Follow the prompts. Rinse and repeat for as many clients as necessary to start the game. Please don't enter invalid gameIDs as bad things may happen. Still need to do input validation. Will most likely remove the textbox so you just click the game name and …
> Lobby backend work

- src/public/lobby.js
- src/routes/lobbyRoutes.cjs
- src/services/lobby.cjs
- src/views/lobby.html
Added the custom word, if the relevant game mode is selected, allowing the user to specify which word is to be guessed. Added the creation of the game in the database.
Related to #59
Shows the number of players selected in the game creation form
> Custom word

- package-lock.json
- package.json
- src/public/game.js
- src/public/lobby.js
- src/views/lobby.html
Just modified the UI so that it looks nice but still behaves exactly how @RogerDMK coded it to :) 
Made it so that if a client joins a game without going through the lobby, they are redirected to the lobby.
Also made it so that a client can just click a 'join game' button in the lobby to join a game.
Related to #59, #55
> Made some minor changes to the UI so that bootstrap components are used

- package-lock.json
- package.json
- src/package-lock.json
- src/package.json
- src/public/login.cjs
- src/services/loginDb.cjs
- src/views/Login.html
- tests/loginDb.test.js
Added password encryption via public key, and updated some checks due to the encrypted password
the database will now store the encrypted password
#65 
Fixed the issue where users would register with a pre-existing username , made username distinct and only one username can be stored in the database
> Password Encryption

- package-lock.json
- package.json
- src/public/game.js
- src/public/lobby.js
- src/services/lobby.cjs
- src/services/socket.cjs
- src/views/lobby.html
The game server now communicates with the database. The standard mode should be fully functional with the ability for users to join games that have been made but do not have enough players to start yet. The word for the players to guess is retrieved from the db.
Related to #55, #58, #59
> Game database

- src/public/changeBackground.js
- src/public/fetchMode.js
- src/public/friends.cjs
- src/public/game.js
- src/public/generalStats.cjs
- src/public/lobby.js
- src/public/settings.cjs
Removed $(document).ready(function) as it is deprecated code, using the recommended alternative of $(function).
#81 
The changes above are a fix
> Fixed deprecated issue

- src/views/game.html
- src/views/lobby.html
Added bootstrap UI elements to improve the look of the lobby UI 
#85
> Lobby layout improvement

- src/public/game.js
- src/public/utils.js
- src/services/lobby.cjs
- src/services/socket.cjs
- src/views/game.html
Changed from using userID to username since this reflects the changes to the db.
Updated queries to use the Username column instead of the UserID column in the db.
Fixed ambiguous column name issue.
Just commented out the settings in the game page for now since enabling them crashes the server.
> Fixed the game page so that it works with the new db layout.

- src/public/game.js
- src/public/lobby.js
- src/views/game.html
Added a popup dialogue that appears when the game is over. It displays who won and the player that won gets a congratulatory message.
Clicking the close button redirects the user to the lobby. At the same time, the session storage is cleared as a precaution.
Also linted the files.
Fixes #55
> Notification on game end

- src/public/fetchMode.js
- src/public/sendToServer.cjs
- src/public/setMode.js
- src/routes/userRoutes.cjs
- src/services/settings_db.cjs
- src/views/home.html
- src/views/settings.html
Dark mode settings now has username input from cookie, mode only updates on refresh... working on it :)
> Settings username update

- src/services/lobby.cjs
- src/services/socket.cjs
All the guesses made by the users for a particular game are now correctly logged.
The user the won a particular game is also saved to the database.
Fixes #15
> Word guess history timestamp bug fix

- src/public/game.css
- src/public/game.js
- src/views/game.html
- src/views/home.html
- src/views/lobby.html
Updated the game and lobby pages to be more standard as well.
#98
> Improved the UI standardisation of the home page

- src/public/fetchBackground.cjs
- src/public/game.css
- src/public/sendBackgroundToServer.js
- src/routes/gameRoutes.cjs
- src/services/background_db.cjs
- src/views/game.html
Change background linked to user account and updated stylesheet
> Change background settings linked to user account

- index.js
- src/public/home.js
- src/views/404.html
- src/views/home.html
Added a 404 page and associated handler to redirect clients to the dedicated page if the resource they request is invalid.
Removed old code from index.js
Added a logout button to the home page.
> Made a 404 page.

- src/services/socket.cjs
Fixed word logging slowing down the entire game.
Fixes #97
> Fixed word logging slowing down the game.

- src/public/fetchMode.js
- src/public/login.cjs
- src/public/setMode.js
- src/public/settings.cjs
- src/views/Login.html
- src/views/home.html
- src/views/settings.html
Dark mode is now stored in cookies and the cookies are updated when the dark mode is changed
Dark mode now uses bootstrap
> Dark Mode Saved in and Loaded from Cookies

- src/public/game.css
- src/views/404.html
- src/views/Login.html
- src/views/Statistics.html
- src/views/about.html
- src/views/changeBackground.html
- src/views/form.html
- src/views/friends.html
- src/views/game.html
- src/views/home.html
- src/views/lobby.html
- src/views/matchHistory.html
- src/views/settings.html
- src/views/test.html
#105 
Added mobile view functionality and improved general responsiveness.
> Responsiveness + mobile view

- package-lock.json
- package.json
- src/public/lobby.js
#85 #98 
Bug fix: added a new minimum players of 3 for custom games.
Also added jquery to the package-lock and package files to ensure it is a dependency.
> Bug fix: added a new minimum players of 3 for custom games

- src/public/friends.cjs
- src/routes/userRoutes.cjs
- src/services/friendsDb.cjs
- src/services/loginDb.cjs
- src/services/matchHistory.cjs
- src/views/friends.html
#56  added functionality to accept and decline friend requests ,some minor UI updates and comments
Updated some bugs regarding friend list #56
> Friends screen friend request

- src/public/darkmode.css
- src/public/fetchMode.js
- src/public/home.js
- src/public/login.cjs
- src/public/sendToServer.cjs
- src/public/setMode.js
- src/views/Statistics.html
- src/views/friends.html
- src/views/game.html
- src/views/home.html
- src/views/lobby.html
- src/views/matchHistory.html
- src/views/settings.html
Dark mode on all pages
Dark mode cookie updates before redirect
> Settings user

- src/public/game.js
- src/services/socket.cjs
If a user tries to join a game that they are already part of, the server stops them from joining and gives them an error.
> User joins game they are already in

- src/public/lobby.js
- src/services/socket.cjs
When a player creates a game, their session storage contains the game type and idenfities them as the creator of the game. If a player joins a game, their session storage contains the type of game.
> Game type now in sessionStorage.

- src/public/game.js
- src/public/lobby.js
- src/services/lobby.cjs
- src/services/socket.cjs
My code got messed up some how..... Fixing it here.
> No player wins

- src/public/game.js
- src/public/lobby.js
- src/services/lobby.cjs
- src/services/socket.cjs
Added prompts to tell players which player won the game and what the word was. Also added prompt to tell the players that none of them guessed the word.
All guesses sent by the player are validated. If the guess is not in our word database, then the guess does not count and the player is told that the word is invalid.
If a user tries to create a custom game with a word that is not in our database, they are given an error.
Close #58 
Close #55
> Validate words + nobody wins

- src/public/generalStats.cjs
- src/public/lobby.js
- src/public/settings.cjs
- src/views/lobby.html
- src/views/statistics.html
- tests/background.test.js
- tests/settings.test.js
Dark mode applies to lobby containers and statistics table
Updated settings tests
> Dark mode improvements

- tests/socket.test.js
Added very basic tests for the back end game server.
> Socket tests

- src/public/game.js
NOTE: "Word contains invalid characters" bug!
#68  improvement
> Last letter bug should be fixed BUT NOTE THE "Word contains invalid characters" bug! 

- src/mainRoutes.cjs
- src/services/loginDb.cjs
- tests/loginDb.test.js
Added the removed function back, and added appropriate test
> getUser function

- src/public/generalStats.cjs
- src/services/matchHistory.cjs
- tests/stats.test.js
> Statistics tests

- src/public/backgroundPopup.cjs
- src/public/generalStats.cjs
- src/public/lobby.js
- src/views/game.html
Dark mode fix in game page
Dark mode hover fix on lobby page
> Dark Mode Fix

- src/public/home.js
Fixes a bug
Page redirect issue is fixed
> Home page redirects

- src/public/game.css
- src/views/game.html
Background button is relative to game heading and all buttons are relative to each other
> Background Button Update

- tests/friendDb.test.js
- tests/loginDb.test.js
Fixed the issue  where jest waits for an async function to finish and it times out
Fixes 
minor fix to the issue where jest keeps running until async function times out
> updated tests

- src/public/friends.cjs
fixed little bug where if there is no friends it does not display that
> bug fix friends list

- src/public/lobby.js
- src/services/socket.cjs
Fixed bug preventing players from finishing a custom game if nobody won.
Prevent users from entering invalid characters in the custom word box.
> Bug fixes for the lobby and custom game

- src/public/lobby.js
> Custom Word Field in Dark Mode

- src/public/game.css
- src/views/game.html
> Background button move
